### ISSUE TITLE
How to handle invalid values in the prompt depth?

### ISSUE THREAD

**Issue by morsingher** [DepthAnything/PromptDA#3]
Hi, I'm interested in reproducing your street reconstruction example (https://promptda.github.io/assets/street_recon.mp4), where typically LiDAR values projected in the image have mostly invalid pixels, as it can be seen in your videos. I was wondering how does the network interpret invalid values? I have my own dataset and I tried to simply set them to 0, but results are pretty bad. Any help would be appreciated :)

**Comment by haotongl** [comment]
Thanks for your interests! The current prompting method is based on CNN, which is sensitive to random blank pixels. For my experiments with vehicle LiDAR, I simply preprocess the input LiDAR with KNN completion (k=4), which greatly improves robustness. Feel free to discuss further if you have more questions.
