### ISSUE TITLE
Is it possible to fine tune the model with face dataset.

### ISSUE THREAD

**Issue by YiChenCityU** [DepthAnything/PromptDA#4]
Hi, it's nice work. I wonder is it helpful for face depth estimation if I fine tune it on human face dataset. What is the dataset size should be? Thanks very much.

**Comment by haotongl** [comment]
Yes, it is possible to fine-tune your method on face data. I believe that the quantity of data is not the key; rather, the diversity of the data and, especially, the similarity between the training data and your target scene are more important. If the scenes are similar, just learning the generalization to faces, I think data of 1-2k images is sufficient. As I found, it’s possible to tune our method on the [THuman 2.0](https://github.com/ytrock/THuman2.0-Dataset) dataset, which includes 500 humans, and it shows improved robustness in human depth estimation.”

**Comment by YiChenCityU** [comment]
Very detailed explaination. Thanks alot.

**Comment by haotongl** [comment]
I’ll close this issue. Feel free to reopen it if you have any more questions!
