### ISSUE TITLE
Great job! Can you release the model fine-tuned on the outdoor data?

### ISSUE THREAD

**Issue by cdb342** [DepthAnything/PromptDA#5]

**Comment by haotongl** [comment]
Yeah, we plan to release it! At the latest, it will be before the official paper publication. Please stay tuned!

**Comment by qsisi** [comment]
Hello! @haotongl Do u still plan to release the model finetuned on SHIFT dataset? Thanks!

**Comment by sarthak247** [comment]
Adding a comment here to follow along for any updates
