### ISSUE TITLE
How to export point cloud like in hf demo with inferred depths

### ISSUE THREAD

**Issue by LaFeuilleMorte** [DepthAnything/PromptDA#6]

**Comment by haotongl** [comment]
Hi, thanks for your interests! Please refer to the following code to transfer a depth map to the point cloud:
https://huggingface.co/spaces/depth-anything/PromptDA/blob/main/app.py#L111-L120

**Comment by LaFeuilleMorte** [comment]
Thanks for your reply. Can I use the odometry translation and quternion to merge all point clouds and do global reconstruction. Or is it better to do rgbd slam with the rgb and depth images?

**Comment by haotongl** [comment]
Yeah, it’s possible to use visual odometry to merge point clouds as our prompting. This requires training a new model.

If you just want a global reconstruction with our iPhone model, you can take the camera poses from ARKit, which are provided by the Stray Scanner app.
