### ISSUE TITLE
Prediction of continuous image sequences taken by non-iPhone devices

### ISSUE THREAD

**Issue by curryandklay** [DepthAnything/PromptDA#7]
Great work! Suppose I only have a continuous sequence of images, not a video, can I still get a view-consistent depth estimate by reusing the model to estimate these continuous images?

**Comment by sctrueew** [comment]
@curryandklay Hello! I hope you’re doing well. Have you managed to find a solution? In my case, I have an RGB video, and I’m looking to predict depth and create a 3D reconstruction. However, I don’t have any LiDAR data, just the 2D video. I’d like to achieve something similar to this.

![image](https://github.com/user-attachments/assets/dfc4efb2-b34d-4cf2-ac08-ccbb02efc21d)

**Comment by curryandklay** [comment]
@sctrueew Gotcha you! This is what I want to achieve with PromptDA! However, it seems that it does not support pure image input at the moment, which was my oversight before I posted the issue. LiDAR input is what the program needs to read.
